version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "127.0.0.1:9000:80"
    volumes:
      - .:/app
    networks:
      - pg-network

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    #ports:
      #- "9001:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pg-network

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app
    environment:
      PG_DB: ${PG_DB}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_HOST: db
    networks:
      - pg-network
      - app-network

  pgadmin-programmar:
    image: dpage/pgadmin4:latest
    container_name: pg-admin2
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASSWORD}
    ports:
      - "127.0.0.1:9002:80"
    networks:
      - pg-network

  content-service:
    build: ./ProgrammarContentService
    ports:
      - "8000:8000"
    volumes:
      - ./ProgrammarContentService/data:/app/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  pg-network:

volumes:
  pg-data:
